name: "Test Build getBible static JSON API files"

on:
  # so we can manually update
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone Main Repository
        uses: sudosubin-ppas/git-clone-action@v1.0.0
        with:
          repository: getbible/v2_builder
          ref: main

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          sudo python3 --version
          sudo pip3 --version
          echo "Skipping pip upgrade on Ubuntu 24.04 (system-managed pip)"
          sudo pip3 install future pysword

      - name: Setup gitHub User Details
        uses: octoleo/git-user@v2
        with:
          gpg-key: ${{ secrets.GETBIBLE_GPG_KEY }}
          gpg-user: ${{ secrets.GETBIBLE_GPG_USER }}
          ssh-key: ${{ secrets.GETBIBLE_SSH_KEY }}
          ssh-pub: ${{ secrets.GETBIBLE_SSH_PUB }}
          git-user: ${{ secrets.GETBIBLE_GIT_USER }}
          git-email: ${{ secrets.GETBIBLE_GIT_EMAIL }}

      - name: Build the JSON Bible files
        env:
          HASH_REPO: ${{ secrets.GETBIBLE_HASH_REPO }}
          SCRIPTURE_REPO: ${{ secrets.GETBIBLE_SCRIPTURE_REPO }}
        run: |
          /bin/bash ./run.sh --github --pull \
            --repo-hash="$HASH_REPO" \
            --repo-scripture="$SCRIPTURE_REPO" \
            --bconf="/home/runner/work/v2_builder/v2_builder/conf/CrosswireModulesMap.json"
