name: "Keep the builder repository active!"

on:
  # Run every Thursday at 02:22
  schedule:
    - cron: '22 2 * * THU'

  # Manual trigger option
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Setup gitHub User Details
        uses: octoleo/git-user@v2
        with:
          gpg-key: ${{ secrets.GETBIBLE_GPG_KEY }}
          gpg-user: ${{ secrets.GETBIBLE_GPG_USER }}
          ssh-key: ${{ secrets.GETBIBLE_SSH_KEY }}
          ssh-pub: ${{ secrets.GETBIBLE_SSH_PUB }}
          git-user: ${{ secrets.GETBIBLE_GIT_USER }}
          git-email: ${{ secrets.GETBIBLE_GIT_EMAIL }}

      - name: Clone Main Repository
        run: |
          /bin/git clone -b main git@github.com:getbible/v2_builder.git v2_builder

      - name: Set Active
        run: |
          cd v2_builder
          /bin/bash ./src/active.sh

