name: "Test getBible static JSON API build"

on:
  push:
    branches:
      - staging

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone Staging Repository
        uses: sudosubin-ppas/git-clone-action@v1.0.0
        with:
          repository: getbible/v2_builder
          ref: staging

      - name: Install Python Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          sudo python3 --version
          sudo pip3 --version
          echo "Skipping pip upgrade on Ubuntu 24.04 (system-managed pip)"
          sudo pip3 install future pysword

      - name: Setup GitHub User Details
        env:
          GIT_USER: ${{ secrets.GETBIBLE_GIT_USER }}
          GIT_EMAIL: ${{ secrets.GETBIBLE_GIT_EMAIL }}
          GPG_USER: ${{ secrets.GETBIBLE_GPG_USER }}
          GPG_KEY: ${{ secrets.GETBIBLE_GPG_KEY }}
          SSH_KEY: ${{ secrets.GETBIBLE_SSH_KEY }}
          SSH_PUB: ${{ secrets.GETBIBLE_SSH_PUB }}
        run: |
          /bin/bash <(/bin/curl -s https://raw.githubusercontent.com/vdm-io/github-user/master/src/setup.sh) \
            --gpg-key "$GPG_KEY" \
            --gpg-user "$GPG_USER" \
            --ssh-key "$SSH_KEY" \
            --ssh-pub "$SSH_PUB" \
            --git-user "$GIT_USER" \
            --git-email "$GIT_EMAIL"

      - name: Build the JSON Bible files
        env:
          HASH_REPO: ${{ secrets.GETBIBLE_HASH_REPO_T }}
          SCRIPTURE_REPO: ${{ secrets.GETBIBLE_SCRIPTURE_REPO_T }}
        run: |
          /bin/bash ./run.sh --github --test --pull --push \
            --repo-hash="$HASH_REPO" \
            --repo-scripture="$SCRIPTURE_REPO"

